name: merenda_escolar
description: A new Flutter application.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1
environment:
  sdk: ">=2.0.0 <3.0.0"
analyzer:
  - enable-experiment:
      - non-nullable
dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.1
  rxdart: ^0.25.0
  http: ^0.12.0+2
  provider: ^4.0.0

  jwt_decoder: ^1.0.3
  font_awesome_flutter: ^8.11.0
  jiffy: ^3.0.1
  key_value_store_web: ^1.0.0
  dbcrypt: ^1.0.0
  brasil_fields: ^0.6.1
  validadores: ^1.0.2
  cpf_cnpj_validator: ^1.0.5
  mask_text_input_formatter: ^1.2.1
  search_page: ^1.4.0
  toast: ^0.1.5
  badges: ^1.1.6
  data_tables: ^1.0.3
  pie_chart: ^4.0.1
  charts_flutter: ^0.9.0
  syncfusion_flutter_charts: ^18.4.39
  fl_chart: ^0.12.2
  graphic: ^0.3.0
  start_chart: ^0.2.0
  flutter_chart_csx: ^0.0.3
  syncfusion_flutter_pdf: ^18.4.41-beta
  search_app_bar_page: ^1.4.2
  google_fonts: ^1.0.0

  pdf: ^2.0.0
  printing: ^4.0.0
  path_provider: ^1.6.5
  open_file: ^3.0.1

  url_launcher: ^5.7.8
  supercharged: ^1.12.0
  shared_preferences: ^0.5.10
  bloc_pattern: ^2.3.2

  get: ^3.11.1
  diacritic: ^0.1.1
  dio: ^3.0.10
  dropdown_search: ^0.4.9
  sembast: ^2.4.10+3
  sembast_web: ^1.2.0+1
  appbar_textfield: ^1.0.1+1
  faker: ^1.3.0
  community_material_icon: ^5.9.55
  step_progress_indicator: ^1.0.0
  line_icons: ^2.0.1
  firebase: ^6.0.0
  modal_bottom_sheet: ^2.0.0
  native_pdf_view: ^4.0.0
  image_web_picker: ^0.0.1
  connectivity: ^3.0.6





dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/imgs/
    - assets/images/
    - assets/images/pdf/
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: roboto
      fonts:
        - asset: assets/fonts/roboto/Roboto-Regular.ttf
        - asset: assets/fonts/roboto/Roboto-Regular.ttf
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
